
package br.com.sgpc.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GrepCep", targetNamespace = "http://ws.grepcepws.com", wsdlLocation = "file:/home/guilherme/Downloads/GrepCep.wsdl")
public class GrepCep
    extends Service
{

    private final static URL GREPCEP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.sgpc.webservice.GrepCep.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.sgpc.webservice.GrepCep.class.getResource(".");
            url = new URL(baseUrl, "file:/home/guilherme/Downloads/GrepCep.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/guilherme/Downloads/GrepCep.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GREPCEP_WSDL_LOCATION = url;
    }

    public GrepCep(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrepCep() {
        super(GREPCEP_WSDL_LOCATION, new QName("http://ws.grepcepws.com", "GrepCep"));
    }

    /**
     * 
     * @return
     *     returns GrepCepPortType
     */
    @WebEndpoint(name = "GrepCepHttpSoap11Endpoint")
    public GrepCepPortType getGrepCepHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ws.grepcepws.com", "GrepCepHttpSoap11Endpoint"), GrepCepPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GrepCepPortType
     */
    @WebEndpoint(name = "GrepCepHttpSoap11Endpoint")
    public GrepCepPortType getGrepCepHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.grepcepws.com", "GrepCepHttpSoap11Endpoint"), GrepCepPortType.class, features);
    }

}
