
package br.com.sgpc.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GrepCepPortType", targetNamespace = "http://ws.grepcepws.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GrepCepPortType {


    /**
     * 
     * @param cep
     * @param token
     * @return
     *     returns br.com.sgpc.webservice.ObterCepResponse
     */
    @WebMethod(action = "urn:obterEnderecoCep")
    @WebResult(targetNamespace = "http://ws.grepcepws.com")
    @RequestWrapper(localName = "obterEnderecoCep", targetNamespace = "http://ws.grepcepws.com", className = "br.com.sgpc.webservice.ObterEnderecoCep")
    @ResponseWrapper(localName = "obterEnderecoCepResponse", targetNamespace = "http://ws.grepcepws.com", className = "br.com.sgpc.webservice.ObterEnderecoCepResponse")
    public ObterCepResponse obterEnderecoCep(
        @WebParam(name = "cep", targetNamespace = "http://ws.grepcepws.com")
        String cep,
        @WebParam(name = "token", targetNamespace = "http://ws.grepcepws.com")
        String token);

}
